<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class NfcController extends Controller
{
    private const BACK  = '/nfc_cards/card-back.jpeg';
    private const INFO  = 'info@shmaliklogistics.co.tz';

    private static array $employees = [

        // ── Management ──────────────────────────────────────────────────────
        'abdulmalik-suleiman-ahmed' => [
            'name'      => 'Abdulmalik Suleiman Ahmed',
            'roles'     => ['Director'],
            'email'     => 'abdulmalik.ahmed@shmaliklogistics.co.tz',
            'phone'     => '+255652373434',
            'idNo'      => '2506-2022-0001',
            'slug'      => 'abdulmalik-suleiman-ahmed',
            'image'     => '/nfc_cards/abdulmalik-suleiman-ahmed.jpeg',
            'backImage' => self::BACK,
        ],
        'mahsen-suleiman-ahmedy' => [
            'name'      => 'Mahsen Suleiman Ahmedy',
            'roles'     => ['Director'],
            'email'     => 'mahsen.ahmedy@shmaliklogistics.co.tz',
            'phone'     => '+255712892222',
            'idNo'      => '2506-2022-0020',
            'slug'      => 'mahsen-suleiman-ahmedy',
            'image'     => '/nfc_cards/mahsen-suleiman-ahmedy.jpeg',
            'backImage' => self::BACK,
        ],
        'ally-ghanim' => [
            'name'      => 'Ally Ghanim Ally',
            'roles'     => ['Operation Manager'],
            'email'     => 'ally.ghanim@shmaliklogistics.co.tz',
            'phone'     => '+255686366657',
            'idNo'      => '2506-2022-0006',
            'slug'      => 'ally-ghanim',
            'image'     => '/nfc_cards/ally-ghanim.jpeg',
            'backImage' => self::BACK,
        ],
        'semwali-stephen-william' => [
            'name'      => 'Semwali Stephen William',
            'roles'     => ['Operation Officer'],
            'email'     => self::INFO,
            'phone'     => '+255654104767',
            'idNo'      => '2506-2022-00105',
            'slug'      => 'semwali-stephen-william',
            'image'     => '/nfc_cards/semwali-stephen-william.jpeg',
            'backImage' => self::BACK,
        ],
        'arkam-ally-salum' => [
            'name'      => 'Arkam Ally Salum',
            'roles'     => ['Assistant Operation Manager'],
            'email'     => 'arkam.salum@shmaliklogistics.co.tz',
            'phone'     => '+255755637742',
            'idNo'      => '2506-2022-0007',
            'slug'      => 'arkam-ally-salum',
            'image'     => '/nfc_cards/arkam-ally-salum.jpeg',
            'backImage' => self::BACK,
        ],
        'kombo-shali-mzee' => [
            'name'      => 'Kombo Shali Mzee',
            'roles'     => ['Supervisor'],
            'email'     => self::INFO,
            'phone'     => '+255753132951',
            'idNo'      => '2506-2022-0012',
            'slug'      => 'kombo-shali-mzee',
            'image'     => '/nfc_cards/kombo-shali-mzee.jpeg',
            'backImage' => self::BACK,
        ],
        'juma-hussein-shindo' => [
            'name'      => 'Juma Hussein Shindo',
            'roles'     => ['Supervisor'],
            'email'     => self::INFO,
            'phone'     => '+255625662181',
            'idNo'      => '2506-2022-0011',
            'slug'      => 'juma-hussein-shindo',
            'image'     => '/nfc_cards/juma-hussein-shindo.jpeg',
            'backImage' => self::BACK,
        ],

        // ── Accounts ────────────────────────────────────────────────────────
        'salim-hilal-salim' => [
            'name'      => 'Salim Hilal Salim',
            'roles'     => ['Head of Accounts'],
            'email'     => 'salim.hila@shmaliklogistics.co.tz',
            'phone'     => '+255713133159',
            'idNo'      => '2506-2022-0002',
            'slug'      => 'salim-hilal-salim',
            'image'     => '/nfc_cards/salim-hilal-salim.jpeg',
            'backImage' => self::BACK,
        ],
        'saheel-abdulqadir' => [
            'name'      => 'Saheel Abdulqadir Gajjar',
            'roles'     => ['Assistant Accountant'],
            'email'     => 'saheel.gajjar@shmaliklogistics.co.tz',
            'phone'     => '+255692409999',
            'idNo'      => '2506-2022-0006',
            'slug'      => 'saheel-abdulqadir',
            'image'     => '/nfc_cards/saheel-abdulqadir.jpeg',
            'backImage' => self::BACK,
        ],
        'shabani-kipingu' => [
            'name'      => 'Shabani Bakari Kipingu',
            'roles'     => ['Assistant Accountant'],
            'email'     => 'shabani.kipingu@shmaliklogistics.co.tz',
            'phone'     => '+255710119189',
            'idNo'      => '2506-2022-0003',
            'slug'      => 'shabani-kipingu',
            'image'     => '/nfc_cards/shabani-kipingu.jpeg',
            'backImage' => self::BACK,
        ],

        // ── IT & HR ──────────────────────────────────────────────────────────
        'towfiq-seif' => [
            'name'      => 'Towfiq Seif Ramadhan',
            'roles'     => ['Head of IT'],
            'email'     => 'towfiq.seif@shmaliklogistics.co.tz',
            'phone'     => '+255789511234',
            'idNo'      => '2506-2022-0004',
            'slug'      => 'towfiq-seif',
            'image'     => '/nfc_cards/towfiq-seif.jpeg',
            'backImage' => self::BACK,
        ],
        'towfiq-seif-hr' => [
            'name'      => 'Towfiq Seif Ramadhan',
            'roles'     => ['Human Resource Manager'],
            'email'     => 'hr@shmaliklogistics.co.tz',
            'phone'     => '+255789511234',
            'idNo'      => '2506-2022-0004',
            'slug'      => 'towfiq-seif-hr',
            'image'     => '/nfc_cards/towfiq-seif-hr.jpeg',
            'backImage' => self::BACK,
        ],

        // ── Engineering ──────────────────────────────────────────────────────
        'ramadhani-salimu-ramadhani' => [
            'name'      => 'Ramadhani Salimu Ramadhani',
            'roles'     => ['Electronics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255619751043',
            'idNo'      => '2506-2022-0008',
            'slug'      => 'ramadhani-salimu-ramadhani',
            'image'     => '/nfc_cards/ramadhani-salimu-ramadhani.jpeg',
            'backImage' => self::BACK,
        ],
        'shabani-saidi-seleman' => [
            'name'      => 'Shabani Saidi Seleman',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255786766844',
            'idNo'      => '2506-2022-0009',
            'slug'      => 'shabani-saidi-seleman',
            'image'     => '/nfc_cards/shabani-saidi-seleman.jpeg',
            'backImage' => self::BACK,
        ],
        'alphonce-fortunatus-kawonga' => [
            'name'      => 'Alphonce Fortunatus Kawonga',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255710173554',
            'idNo'      => '2506-2022-0010',
            'slug'      => 'alphonce-fortunatus-kawonga',
            'image'     => '/nfc_cards/alphonce-fortunatus-kawonga.jpeg',
            'backImage' => self::BACK,
        ],
        'juma-rehani-rajabu' => [
            'name'      => 'Juma Rehani Rajabu',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255742558908',
            'idNo'      => '2506-2022-0017',
            'slug'      => 'juma-rehani-rajabu',
            'image'     => '/nfc_cards/juma-rehani-rajabu.jpeg',
            'backImage' => self::BACK,
        ],
        'hamad-juma-chande' => [
            'name'      => 'Hamad Juma Chande',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255718213199',
            'idNo'      => '2506-2022-0018',
            'slug'      => 'hamad-juma-chande',
            'image'     => '/nfc_cards/hamad-juma-chande.jpeg',
            'backImage' => self::BACK,
        ],
        'danford-erasto-nyoni' => [
            'name'      => 'Danford Erasto Nyoni',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255711980014',
            'idNo'      => '2506-2022-0019',
            'slug'      => 'danford-erasto-nyoni',
            'image'     => '/nfc_cards/danford-erasto-nyoni.jpeg',
            'backImage' => self::BACK,
        ],
        'ramadhan-issa-mpomo' => [
            'name'      => 'Ramadhan Issa Mpomo',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255697686650',
            'idNo'      => '2506-2022-0021',
            'slug'      => 'ramadhan-issa-mpomo',
            'image'     => '/nfc_cards/ramadhan-issa-mpomo.jpeg',
            'backImage' => self::BACK,
        ],
        'maxmillian-baraka-mtui' => [
            'name'      => 'Maxmilian Baraka Mtui',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255625452581',
            'idNo'      => '2506-2022-0022',
            'slug'      => 'maxmillian-baraka-mtui',
            'image'     => '/nfc_cards/maxmillian-baraka-mtui.jpeg',
            'backImage' => self::BACK,
        ],
        'khalifan-shaban-rajabu' => [
            'name'      => 'Khalifan Shaban Rajabu',
            'roles'     => ['Electronics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255680088200',
            'idNo'      => '2506-2022-0023',
            'slug'      => 'khalifan-shaban-rajabu',
            'image'     => '/nfc_cards/khalifan-shaban-rajabu.jpeg',
            'backImage' => self::BACK,
        ],
        'abdurahman-ramadhan-maneno' => [
            'name'      => 'Abdurahman Ramadhan Maneno',
            'roles'     => ['Electronics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255623454942',
            'idNo'      => '2506-2022-0024',
            'slug'      => 'abdurahman-ramadhan-maneno',
            'image'     => '/nfc_cards/abdurahman-ramadhan-maneno.jpeg',
            'backImage' => self::BACK,
        ],
        'ramadhani-rashid-hassan' => [
            'name'      => 'Ramadhani Rashid Hassan',
            'roles'     => ['Welder'],
            'email'     => self::INFO,
            'phone'     => '+255672755323',
            'idNo'      => '2506-2022-0025',
            'slug'      => 'ramadhani-rashid-hassan',
            'image'     => '/nfc_cards/ramadhani-rashid-hassan.jpeg',
            'backImage' => self::BACK,
        ],
        'alhaji-athumani-yahaya' => [
            'name'      => 'Alhaji Athumani Yahaya',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255788353980',
            'idNo'      => '2506-2022-0026',
            'slug'      => 'alhaji-athumani-yahaya',
            'image'     => '/nfc_cards/alhaji-athumani-yahaya.jpeg',
            'backImage' => self::BACK,
        ],
        'mohammed-abdallah-mohammed' => [
            'name'      => 'Mohammed Abdallah Mohammed',
            'roles'     => ['Electronics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255776055333',
            'idNo'      => '2506-2022-0027',
            'slug'      => 'mohammed-abdallah-mohammed',
            'image'     => '/nfc_cards/mohammed-abdallah-mohammed.jpeg',
            'backImage' => self::BACK,
        ],
        'shabani-mustafa-sengo' => [
            'name'      => 'Shabani Mustafa Sengo',
            'roles'     => ['Tyre Expert'],
            'email'     => self::INFO,
            'phone'     => '+255615831444',
            'idNo'      => '2506-2022-0028',
            'slug'      => 'shabani-mustafa-sengo',
            'image'     => '/nfc_cards/shabani-mustafa-sengo.jpeg',
            'backImage' => self::BACK,
        ],
        'yasini-maulidi-shomvi' => [
            'name'      => 'Yasini Maulidi Shomvi',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255693717152',
            'idNo'      => '2506-2022-0029',
            'slug'      => 'yasini-maulidi-shomvi',
            'image'     => '/nfc_cards/yasini-maulidi-shomvi.jpeg',
            'backImage' => self::BACK,
        ],
        'abdallah-sija-abdallah' => [
            'name'      => 'Abdallah Sija Abdallah',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255719439075',
            'idNo'      => '2506-2022-0016',
            'slug'      => 'abdallah-sija-abdallah',
            'image'     => '/nfc_cards/abdallah-sija-abdallah.jpeg',
            'backImage' => self::BACK,
        ],
        'ally-kassim-kilua' => [
            'name'      => 'Ally Kassim Kilua',
            'roles'     => ['Electronics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255663965632',
            'idNo'      => '2506-2022-00106',
            'slug'      => 'ally-kassim-kilua',
            'image'     => '/nfc_cards/ally-kassim-kilua.jpeg',
            'backImage' => self::BACK,
        ],
        'ally-kassim-kilua-mechanics' => [
            'name'      => 'Ally Kassim Kilua',
            'roles'     => ['Mechanics Engineer'],
            'email'     => self::INFO,
            'phone'     => '+255663965632',
            'idNo'      => '2506-2022-0020',
            'slug'      => 'ally-kassim-kilua-mechanics',
            'image'     => '/nfc_cards/ally-kassim-kilua-mechanics.jpeg',
            'backImage' => self::BACK,
        ],

        // ── Drivers ──────────────────────────────────────────────────────────
        'athuman-omary-abdallah' => [
            'name'      => 'Athumani Omary Abdallah',
            'roles'     => ['Driver'],
            'email'     => 'athuman.abdallah@shmaliklogistics.co.tz',
            'phone'     => '+255676711174',
            'idNo'      => '2506-2022-0082',
            'slug'      => 'athuman-omary-abdallah',
            'image'     => '/nfc_cards/athuman-omary-abdallah.jpeg',
            'backImage' => self::BACK,
        ],
        'abdallah-bakari-athuman' => [
            'name'      => 'Abdallah Bakari Athuman',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255696058226',
            'idNo'      => '2506-2022-0087',
            'slug'      => 'abdallah-bakari-athuman',
            'image'     => '/nfc_cards/abdallah-bakari-athuman.jpeg',
            'backImage' => self::BACK,
        ],
        'abushiri-ayoub-juma' => [
            'name'      => 'Abushiri Ayoub Juma',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255622160910',
            'idNo'      => '2506-2022-0042',
            'slug'      => 'abushiri-ayoub-juma',
            'image'     => '/nfc_cards/abushiri-ayoub-juma.jpeg',
            'backImage' => self::BACK,
        ],
        'abubakari-juma-ligonjara' => [
            'name'      => 'Abubakari Juma Ligonjara',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255711726928',
            'idNo'      => '2506-2022-0048',
            'slug'      => 'abubakari-juma-ligonjara',
            'image'     => '/nfc_cards/abubakari-juma-ligonjara.jpeg',
            'backImage' => self::BACK,
        ],
        'abdala-hamisi-abdala' => [
            'name'      => 'Abdala Hamisi Abdala',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255655969617',
            'idNo'      => '2506-2022-0072',
            'slug'      => 'abdala-hamisi-abdala',
            'image'     => '/nfc_cards/abdala-hamisi-abdala.jpeg',
            'backImage' => self::BACK,
        ],
        'aron-joseph-mlambo' => [
            'name'      => 'Aron Joseph Mlambo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255756586463',
            'idNo'      => '2506-2022-0081',
            'slug'      => 'aron-joseph-mlambo',
            'image'     => '/nfc_cards/aron-joseph-mlambo.jpeg',
            'backImage' => self::BACK,
        ],
        'abasi-hatibu-waziri' => [
            'name'      => 'Abasi Hatibu Waziri',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255654946792',
            'idNo'      => '2506-2022-0109',
            'slug'      => 'abasi-hatibu-waziri',
            'image'     => '/nfc_cards/abasi-hatibu-waziri.jpeg',
            'backImage' => self::BACK,
        ],
        'aziz-hassan-seleman' => [
            'name'      => 'Aziz Hassan Seleman',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255674810240',
            'idNo'      => '2506-2022-0055',
            'slug'      => 'aziz-hassan-seleman',
            'image'     => '/nfc_cards/aziz-hassan-seleman.jpeg',
            'backImage' => self::BACK,
        ],
        'bakari-gube-bakari' => [
            'name'      => 'Bakari Gube Bakari',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255692349996',
            'idNo'      => '2506-2022-0057',
            'slug'      => 'bakari-gube-bakari',
            'image'     => '/nfc_cards/bakari-gube-bakari.jpeg',
            'backImage' => self::BACK,
        ],
        'bakari-salimu-hemedi' => [
            'name'      => 'Bakari Salimu Hemedi',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255794244739',
            'idNo'      => '2506-2022-0038',
            'slug'      => 'bakari-salimu-hemedi',
            'image'     => '/nfc_cards/bakari-salimu-hemedi.jpeg',
            'backImage' => self::BACK,
        ],
        'bilaly-ally-bilaly' => [
            'name'      => 'Bilaly Ally Bilaly',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255782157494',
            'idNo'      => '2506-2022-0069',
            'slug'      => 'bilaly-ally-bilaly',
            'image'     => '/nfc_cards/bilaly-ally-bilaly.jpeg',
            'backImage' => self::BACK,
        ],
        'boniface-faustin-seoya' => [
            'name'      => 'Boniface Faustin Seoya',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255784415976',
            'idNo'      => '2506-2022-0039',
            'slug'      => 'boniface-faustin-seoya',
            'image'     => '/nfc_cards/boniface-faustin-seoya.jpeg',
            'backImage' => self::BACK,
        ],
        'christopher-emanuel-eunyo' => [
            'name'      => 'Christopher Emanuel Eunyo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255745100802',
            'idNo'      => '2506-2022-0086',
            'slug'      => 'christopher-emanuel-eunyo',
            'image'     => '/nfc_cards/christopher-emanuel-eunyo.jpeg',
            'backImage' => self::BACK,
        ],
        'fadhil-athuman-kiwanda' => [
            'name'      => 'Fadhil Athuman Kiwanda',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255763380038',
            'idNo'      => '2506-2022-0088',
            'slug'      => 'fadhil-athuman-kiwanda',
            'image'     => '/nfc_cards/fadhil-athuman-kiwanda.jpeg',
            'backImage' => self::BACK,
        ],
        'fadhili-abubakar-gwila' => [
            'name'      => 'Fadhili Abubakar Gwila',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255714138587',
            'idNo'      => '2506-2022-00107',
            'slug'      => 'fadhili-abubakar-gwila',
            'image'     => '/nfc_cards/fadhili-abubakar-gwila.jpeg',
            'backImage' => self::BACK,
        ],
        'frank-raphael-mandanda' => [
            'name'      => 'Frank Raphael Mandanda',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255732697664',
            'idNo'      => '2506-2022-0080',
            'slug'      => 'frank-raphael-mandanda',
            'image'     => '/nfc_cards/frank-raphael-mandanda.jpeg',
            'backImage' => self::BACK,
        ],
        'hamza-kondo-mijafa' => [
            'name'      => 'Hamza Kondo Mijafa',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255712851261',
            'idNo'      => '2506-2022-0102',
            'slug'      => 'hamza-kondo-mijafa',
            'image'     => '/nfc_cards/hamza-kondo-mijafa.jpeg',
            'backImage' => self::BACK,
        ],
        'hassan-mnanka-marwa' => [
            'name'      => 'Hassan Mnanka Marwa',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255782033596',
            'idNo'      => '2506-2022-0079',
            'slug'      => 'hassan-mnanka-marwa',
            'image'     => '/nfc_cards/hassan-mnanka-marwa.jpeg',
            'backImage' => self::BACK,
        ],
        'hussein-said-baadaye' => [
            'name'      => 'Hussein Said Baadaye',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255717139188',
            'idNo'      => '2506-2022-0091',
            'slug'      => 'hussein-said-baadaye',
            'image'     => '/nfc_cards/hussein-said-baadaye.jpeg',
            'backImage' => self::BACK,
        ],
        'iddi-abubakari-hamisi' => [
            'name'      => 'Iddi Abubakari Hamisi',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255718160707',
            'idNo'      => '2506-2022-0086',
            'slug'      => 'iddi-abubakari-hamisi',
            'image'     => '/nfc_cards/iddi-abubakari-hamisi.jpeg',
            'backImage' => self::BACK,
        ],
        'isaya-paulo-kidugo' => [
            'name'      => 'Isaya Paulo Kidugo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255714803290',
            'idNo'      => '2506-2022-0083',
            'slug'      => 'isaya-paulo-kidugo',
            'image'     => '/nfc_cards/isaya-paulo-kidugo.jpeg',
            'backImage' => self::BACK,
        ],
        'issa-kassimu-michael' => [
            'name'      => 'Issa Kassimu Michael',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255695106055',
            'idNo'      => '2506-2022-0051',
            'slug'      => 'issa-kassimu-michael',
            'image'     => '/nfc_cards/issa-kassimu-michael.jpeg',
            'backImage' => self::BACK,
        ],
        'jumbe-jumanne-ramadhani' => [
            'name'      => 'Jumbe Jumanne Ramadhani',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255759003021',
            'idNo'      => '2506-2022-0063',
            'slug'      => 'jumbe-jumanne-ramadhani',
            'image'     => '/nfc_cards/jumbe-jumanne-ramadhani.jpeg',
            'backImage' => self::BACK,
        ],
        'khamisi-imamu-athumani' => [
            'name'      => 'Khamisi Imamu Athumani',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255746848483',
            'idNo'      => '2506-2022-0085',
            'slug'      => 'khamisi-imamu-athumani',
            'image'     => '/nfc_cards/khamisi-imamu-athumani.jpeg',
            'backImage' => self::BACK,
        ],
        'masudi-ally-almasi' => [
            'name'      => 'Masudi Ally Almasi',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255794617802',
            'idNo'      => '2506-2022-0050',
            'slug'      => 'masudi-ally-almasi',
            'image'     => '/nfc_cards/masudi-ally-almasi.jpeg',
            'backImage' => self::BACK,
        ],
        'meckfason-jared-mawala' => [
            'name'      => 'Meckfason Jared Mawala',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255787593289',
            'idNo'      => '2506-2022-0100',
            'slug'      => 'meckfason-jared-mawala',
            'image'     => '/nfc_cards/meckfason-jared-mawala.jpeg',
            'backImage' => self::BACK,
        ],
        'michael-venance-siogo' => [
            'name'      => 'Michael Venance Siogo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255766160042',
            'idNo'      => '2506-2022-0090',
            'slug'      => 'michael-venance-siogo',
            'image'     => '/nfc_cards/michael-venance-siogo.jpeg',
            'backImage' => self::BACK,
        ],
        'miraji-ramadhani-alute' => [
            'name'      => 'Miraji Ramadhani Alute',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255742576629',
            'idNo'      => '2506-2022-0074',
            'slug'      => 'miraji-ramadhani-alute',
            'image'     => '/nfc_cards/miraji-ramadhani-alute.jpeg',
            'backImage' => self::BACK,
        ],
        'mohamed-ally-ngoji' => [
            'name'      => 'Mohamed Ally Ngoji',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255659270385',
            'idNo'      => '2506-2022-0052',
            'slug'      => 'mohamed-ally-ngoji',
            'image'     => '/nfc_cards/mohamed-ally-ngoji.jpeg',
            'backImage' => self::BACK,
        ],
        'mohamed-nduku-juma' => [
            'name'      => 'Mohamed Nduku Juma',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255716737241',
            'idNo'      => '2506-2022-0064',
            'slug'      => 'mohamed-nduku-juma',
            'image'     => '/nfc_cards/mohamed-nduku-juma.jpeg',
            'backImage' => self::BACK,
        ],
        'nyanda-amon-nason' => [
            'name'      => 'Nyanda Amon Nason',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255712246028',
            'idNo'      => '2506-2022-0098',
            'slug'      => 'nyanda-amon-nason',
            'image'     => '/nfc_cards/nyanda-amon-nason.jpeg',
            'backImage' => self::BACK,
        ],
        'ramadhani-ashibaye-salum' => [
            'name'      => 'Ramadhani Ashibaye Salum',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255783621717',
            'idNo'      => '2506-2022-0071',
            'slug'      => 'ramadhani-ashibaye-salum',
            'image'     => '/nfc_cards/ramadhani-ashibaye-salum.jpeg',
            'backImage' => self::BACK,
        ],
        'ramadhani-shabani-nyangala' => [
            'name'      => 'Ramadhani Shabani Nyangala',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255744498181',
            'idNo'      => '2506-2022-0067',
            'slug'      => 'ramadhani-shabani-nyangala',
            'image'     => '/nfc_cards/ramadhani-shabani-nyangala.jpeg',
            'backImage' => self::BACK,
        ],
        'ramadhani-shabani-ramadhani' => [
            'name'      => 'Ramadhani Shabani Ramadhani',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255656177330',
            'idNo'      => '2506-2022-00108',
            'slug'      => 'ramadhani-shabani-ramadhani',
            'image'     => '/nfc_cards/ramadhani-shabani-ramadhani.jpeg',
            'backImage' => self::BACK,
        ],
        'rashid-yusuph-mbogo' => [
            'name'      => 'Rashid Yusuph Mbogo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255713660748',
            'idNo'      => '2506-2022-0073',
            'slug'      => 'rashid-yusuph-mbogo',
            'image'     => '/nfc_cards/rashid-yusuph-mbogo.jpeg',
            'backImage' => self::BACK,
        ],
        'robsoni-mabula-sumisumi' => [
            'name'      => 'Robsoni Mabula Sumisumi',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255627345360',
            'idNo'      => '2506-2022-0046',
            'slug'      => 'robsoni-mabula-sumisumi',
            'image'     => '/nfc_cards/robsoni-mabula-sumisumi.jpeg',
            'backImage' => self::BACK,
        ],
        'sadiki-hassan-kheri' => [
            'name'      => 'Sadiki Hassan Kheri',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255629401299',
            'idNo'      => '2506-2022-0065',
            'slug'      => 'sadiki-hassan-kheri',
            'image'     => '/nfc_cards/sadiki-hassan-kheri.jpeg',
            'backImage' => self::BACK,
        ],
        'salum-omary-kombo' => [
            'name'      => 'Salum Omary Kombo',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255658764651',
            'idNo'      => '2506-2022-0041',
            'slug'      => 'salum-omary-kombo',
            'image'     => '/nfc_cards/salum-omary-kombo.jpeg',
            'backImage' => self::BACK,
        ],
        'sefu-shafii-msuya' => [
            'name'      => 'Sefu Shafii Msuya',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255715958417',
            'idNo'      => '2506-2022-0110',
            'slug'      => 'sefu-shafii-msuya',
            'image'     => '/nfc_cards/sefu-shafii-msuya.jpeg',
            'backImage' => self::BACK,
        ],
        'shabani-hussein-abbasi' => [
            'name'      => 'Shabani Hussein Abbasi',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255774670435',
            'idNo'      => '2506-2022-0101',
            'slug'      => 'shabani-hussein-abbasi',
            'image'     => '/nfc_cards/shabani-hussein-abbasi.jpeg',
            'backImage' => self::BACK,
        ],
        'shukuru-amri-kibwana' => [
            'name'      => 'Shukuru Amri Kibwana',
            'roles'     => ['Driver'],
            'email'     => self::INFO,
            'phone'     => '+255787000049',
            'idNo'      => '2506-2022-0092',
            'slug'      => 'shukuru-amri-kibwana',
            'image'     => '/nfc_cards/shukuru-amri-kibwana.jpeg',
            'backImage' => self::BACK,
        ],
    ];

    public function show(string $slug)
    {
        $employee = self::$employees[$slug] ?? null;

        if (! $employee) {
            abort(404);
        }

        return Inertia::render('website/StaffCard', [
            'employee' => $employee,
        ]);
    }

    public function index()
    {
        // De-duplicate by slug for the grid view
        $seen = [];
        $list = [];
        foreach (self::$employees as $emp) {
            if (! in_array($emp['slug'], $seen)) {
                $seen[]  = $emp['slug'];
                $list[]  = $emp;
            }
        }

        return Inertia::render('website/Team', [
            'employees' => $list,
        ]);
    }
}
